name: jaspr_lucide
description: Jaspr SVG components for Lucide.
version: 0.1.0
homepage: https://github.com/dazemc/jaspr_lucide
repository: https://github.com/dazemc/jaspr_lucide.git
issue_tracker: https://github.com/dazemc/jaspr_lucide/issues
documentation: https://github.com/dazemc/jaspr_lucide/wiki

environment:
  sdk: ^3.7.2

dependencies:
  xml: ^6.5.0
  jaspr: '>=0.18.0 <0.20.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
